fig08x007<-function(){
#
require(ggplot2)
#
graphics.off()
windows(width=4.5,height=4.5)
#
haireye<-matrix(data=c(7,10,16,94,26,14,14,17,119,54,
29,84,68,15,5,20),nrow=4,ncol=4,byrow=TRUE,
dimnames=list(c("Blond","Red","Brunette","Black"),
c("Brown","Hazel","Green","Blue")))
#
haircol<-unlist(dimnames(haireye)[1])
eyecol<-unlist(dimnames(haireye)[2])
#
hair<-rep(" ",16)
eye<-rep(" ",16)
freq<-rep(0,16)
#
n=0
#
for (i in 1:4){ for (j in 1:4){
n<-n+1
hair[n]<-haircol[i]
eye[n]<-eyecol[j]
freq[n]<-haireye[i,j]
}}
#
hair<-factor(hair,levels=haircol,ordered=TRUE)
eye<-factor(eye,levels=eyecol,ordered=TRUE)
#
he<-freq
nhe<-length(he)
hesum<-sum(he)
he<-he/sum(he)
sd<-sqrt((1.-he)*he/hesum)
hlo<-he-sd
hhi<-he+sd
sd2<-sd*qnorm(0.975)
hlo2<-he-sd2
hhi2<-he+sd2
#
haireyerf<-data.frame(hair=hair,eye=eye,he=he,
hlo=hlo,hhi=hhi,hlo2=hlo2,hhi2=hhi2)
#
figure<-ggplot(haireyerf,aes(x=hair,y=he))+
geom_pointrange(aes(shape=factor(eye,
levels=rev(eyecol),ordered=TRUE),ymin=he,ymax=he,
color=factor(eye,levels=rev(eyecol),ordered=TRUE)),
position=position_dodge(width=0.5),linetype=0)+
geom_errorbar(aes(ymin=hlo,ymax=hhi,
color=factor(eye,levels=rev(eyecol),ordered=TRUE)),
position=position_dodge(width=0.5),linetype=1,width=0.3)+
geom_errorbar(aes(ymin=hlo2,ymax=hhi2,
color=factor(eye,levels=rev(eyecol),ordered=TRUE)),
position=position_dodge(width=0.5),linetype=1,width=0)+
scale_shape_manual(values=15:18)+
scale_color_manual(values=c("blue","green4",
"darkgoldenrod3","brown4"))+
labs(x="Hair Color",y="Relative Frequency",
shape="Eye Color",color="Eye Color")+
guides(shape=guide_legend(reverse=TRUE),
color=guide_legend(reverse=TRUE))+
theme(panel.grid=element_blank())+
coord_flip()
#
print(figure)
#
dev.copy2eps(file="fig08x007.eps",colormodel="cmyk")
dev.copy2pdf(file="fig08x007.pdf",colormodel="cmyk")
}

